# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-28 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.PositiveIntegerField()),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.PositiveIntegerField()),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=30)),
                ('cep', models.PositiveIntegerField()),
            ],
        ),
    ]
